package model;
// Generated Oct 30, 2016 1:24:18 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CitaMedica generated by hbm2java
 */
public class CitaMedica  implements java.io.Serializable {


     private BigDecimal codCitaMedica;
     private Paciente paciente;
     private Turno turno;
     private Date fecha;
     private Date fechaModificacion;
     private char estado;

    public CitaMedica() {
    }

    public CitaMedica(BigDecimal codCitaMedica, Paciente paciente, Turno turno, Date fecha, Date fechaModificacion, char estado) {
       this.codCitaMedica = codCitaMedica;
       this.paciente = paciente;
       this.turno = turno;
       this.fecha = fecha;
       this.fechaModificacion = fechaModificacion;
       this.estado = estado;
    }
   
    public BigDecimal getCodCitaMedica() {
        return this.codCitaMedica;
    }
    
    public void setCodCitaMedica(BigDecimal codCitaMedica) {
        this.codCitaMedica = codCitaMedica;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


