package model;
// Generated Nov 10, 2016 6:17:23 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetalleRecetaMedicaId generated by hbm2java
 */
public class DetalleRecetaMedicaId  implements java.io.Serializable {


     private String codMedicamento;
     private BigDecimal codDiagnostico;

    public DetalleRecetaMedicaId() {
    }

    public DetalleRecetaMedicaId(String codMedicamento, BigDecimal codDiagnostico) {
       this.codMedicamento = codMedicamento;
       this.codDiagnostico = codDiagnostico;
    }
   
    public String getCodMedicamento() {
        return this.codMedicamento;
    }
    
    public void setCodMedicamento(String codMedicamento) {
        this.codMedicamento = codMedicamento;
    }
    public BigDecimal getCodDiagnostico() {
        return this.codDiagnostico;
    }
    
    public void setCodDiagnostico(BigDecimal codDiagnostico) {
        this.codDiagnostico = codDiagnostico;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleRecetaMedicaId) ) return false;
		 DetalleRecetaMedicaId castOther = ( DetalleRecetaMedicaId ) other; 
         
		 return ( (this.getCodMedicamento()==castOther.getCodMedicamento()) || ( this.getCodMedicamento()!=null && castOther.getCodMedicamento()!=null && this.getCodMedicamento().equals(castOther.getCodMedicamento()) ) )
 && ( (this.getCodDiagnostico()==castOther.getCodDiagnostico()) || ( this.getCodDiagnostico()!=null && castOther.getCodDiagnostico()!=null && this.getCodDiagnostico().equals(castOther.getCodDiagnostico()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodMedicamento() == null ? 0 : this.getCodMedicamento().hashCode() );
         result = 37 * result + ( getCodDiagnostico() == null ? 0 : this.getCodDiagnostico().hashCode() );
         return result;
   }   


}


