package model;
// Generated Nov 22, 2016 11:28:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * HistorialClinico generated by hbm2java
 */
public class HistorialClinico  implements java.io.Serializable {


     private String numeroHistorialClinico;
     private Paciente paciente;
     private Set diagnosticos = new HashSet(0);

    public HistorialClinico() {
    }

	
    public HistorialClinico(String numeroHistorialClinico, Paciente paciente) {
        this.numeroHistorialClinico = numeroHistorialClinico;
        this.paciente = paciente;
    }
    public HistorialClinico(String numeroHistorialClinico, Paciente paciente, Set diagnosticos) {
       this.numeroHistorialClinico = numeroHistorialClinico;
       this.paciente = paciente;
       this.diagnosticos = diagnosticos;
    }
   
    public String getNumeroHistorialClinico() {
        return this.numeroHistorialClinico;
    }
    
    public void setNumeroHistorialClinico(String numeroHistorialClinico) {
        this.numeroHistorialClinico = numeroHistorialClinico;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Set getDiagnosticos() {
        return this.diagnosticos;
    }
    
    public void setDiagnosticos(Set diagnosticos) {
        this.diagnosticos = diagnosticos;
    }




}


