package model;
// Generated Nov 24, 2016 2:14:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * HistorialClinico generated by hbm2java
 */
public class HistorialClinico  implements java.io.Serializable {


     private String numeroHistorialClinico;
     private Paciente paciente;
     private String antecedentes;
     private String tipoSangre;
     private Set diagnosticos = new HashSet(0);

    public HistorialClinico() {
    }

	
    public HistorialClinico(String numeroHistorialClinico, Paciente paciente) {
        this.numeroHistorialClinico = numeroHistorialClinico;
        this.paciente = paciente;
    }
    public HistorialClinico(String numeroHistorialClinico, Paciente paciente, String antecedentes, String tipoSangre, Set diagnosticos) {
       this.numeroHistorialClinico = numeroHistorialClinico;
       this.paciente = paciente;
       this.antecedentes = antecedentes;
       this.tipoSangre = tipoSangre;
       this.diagnosticos = diagnosticos;
    }
   
    public String getNumeroHistorialClinico() {
        return this.numeroHistorialClinico;
    }
    
    public void setNumeroHistorialClinico(String numeroHistorialClinico) {
        this.numeroHistorialClinico = numeroHistorialClinico;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public String getAntecedentes() {
        return this.antecedentes;
    }
    
    public void setAntecedentes(String antecedentes) {
        this.antecedentes = antecedentes;
    }
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public Set getDiagnosticos() {
        return this.diagnosticos;
    }
    
    public void setDiagnosticos(Set diagnosticos) {
        this.diagnosticos = diagnosticos;
    }




}


