package model;
// Generated Oct 30, 2016 1:24:18 AM by Hibernate Tools 4.3.1



/**
 * Medicamento generated by hbm2java
 */
public class Medicamento  implements java.io.Serializable {


     private String codMedicamento;
     private String nombre;
     private String descripcion;

    public Medicamento() {
    }

    public Medicamento(String codMedicamento, String nombre, String descripcion) {
       this.codMedicamento = codMedicamento;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public String getCodMedicamento() {
        return this.codMedicamento;
    }
    
    public void setCodMedicamento(String codMedicamento) {
        this.codMedicamento = codMedicamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


