package model;
// Generated Nov 22, 2016 2:50:49 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo  implements java.io.Serializable {


     private BigDecimal codModulo;
     private Perfil perfil;
     private String nombre;
     private String direccion;
     private char estado;
     private Set subModulos = new HashSet(0);

    public Modulo() {
    }

	
    public Modulo(BigDecimal codModulo, Perfil perfil, String nombre, String direccion, char estado) {
        this.codModulo = codModulo;
        this.perfil = perfil;
        this.nombre = nombre;
        this.direccion = direccion;
        this.estado = estado;
    }
    public Modulo(BigDecimal codModulo, Perfil perfil, String nombre, String direccion, char estado, Set subModulos) {
       this.codModulo = codModulo;
       this.perfil = perfil;
       this.nombre = nombre;
       this.direccion = direccion;
       this.estado = estado;
       this.subModulos = subModulos;
    }
   
    public BigDecimal getCodModulo() {
        return this.codModulo;
    }
    
    public void setCodModulo(BigDecimal codModulo) {
        this.codModulo = codModulo;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getSubModulos() {
        return this.subModulos;
    }
    
    public void setSubModulos(Set subModulos) {
        this.subModulos = subModulos;
    }




}


