package model;
// Generated Nov 24, 2016 2:14:55 AM by Hibernate Tools 4.3.1



/**
 * Muestra generated by hbm2java
 */
public class Muestra  implements java.io.Serializable {


     private MuestraId id;
     private Indicador indicador;
     private OrdenMedico ordenMedico;
     private String resultadoMuestra;

    public Muestra() {
    }

	
    public Muestra(MuestraId id, Indicador indicador, OrdenMedico ordenMedico) {
        this.id = id;
        this.indicador = indicador;
        this.ordenMedico = ordenMedico;
    }
    public Muestra(MuestraId id, Indicador indicador, OrdenMedico ordenMedico, String resultadoMuestra) {
       this.id = id;
       this.indicador = indicador;
       this.ordenMedico = ordenMedico;
       this.resultadoMuestra = resultadoMuestra;
    }
   
    public MuestraId getId() {
        return this.id;
    }
    
    public void setId(MuestraId id) {
        this.id = id;
    }
    public Indicador getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(Indicador indicador) {
        this.indicador = indicador;
    }
    public OrdenMedico getOrdenMedico() {
        return this.ordenMedico;
    }
    
    public void setOrdenMedico(OrdenMedico ordenMedico) {
        this.ordenMedico = ordenMedico;
    }
    public String getResultadoMuestra() {
        return this.resultadoMuestra;
    }
    
    public void setResultadoMuestra(String resultadoMuestra) {
        this.resultadoMuestra = resultadoMuestra;
    }




}


