package model;
// Generated Nov 22, 2016 1:56:10 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenMedico generated by hbm2java
 */
public class OrdenMedico  implements java.io.Serializable {


     private BigDecimal codDiagnostico;
     private Diagnostico diagnostico;
     private String tecnologo;
     private Date fechaEjecucion;
     private String estadoPago;
     private String cajero;
     private char estado;
     private Set muestras = new HashSet(0);

    public OrdenMedico() {
    }

	
    public OrdenMedico(Diagnostico diagnostico, String estadoPago, char estado) {
        this.diagnostico = diagnostico;
        this.estadoPago = estadoPago;
        this.estado = estado;
    }
    public OrdenMedico(Diagnostico diagnostico, String tecnologo, Date fechaEjecucion, String estadoPago, String cajero, char estado, Set muestras) {
       this.diagnostico = diagnostico;
       this.tecnologo = tecnologo;
       this.fechaEjecucion = fechaEjecucion;
       this.estadoPago = estadoPago;
       this.cajero = cajero;
       this.estado = estado;
       this.muestras = muestras;
    }
   
    public BigDecimal getCodDiagnostico() {
        return this.codDiagnostico;
    }
    
    public void setCodDiagnostico(BigDecimal codDiagnostico) {
        this.codDiagnostico = codDiagnostico;
    }
    public Diagnostico getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(Diagnostico diagnostico) {
        this.diagnostico = diagnostico;
    }
    public String getTecnologo() {
        return this.tecnologo;
    }
    
    public void setTecnologo(String tecnologo) {
        this.tecnologo = tecnologo;
    }
    public Date getFechaEjecucion() {
        return this.fechaEjecucion;
    }
    
    public void setFechaEjecucion(Date fechaEjecucion) {
        this.fechaEjecucion = fechaEjecucion;
    }
    public String getEstadoPago() {
        return this.estadoPago;
    }
    
    public void setEstadoPago(String estadoPago) {
        this.estadoPago = estadoPago;
    }
    public String getCajero() {
        return this.cajero;
    }
    
    public void setCajero(String cajero) {
        this.cajero = cajero;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getMuestras() {
        return this.muestras;
    }
    
    public void setMuestras(Set muestras) {
        this.muestras = muestras;
    }




}


