package model;
// Generated Nov 10, 2016 6:17:23 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenMedico generated by hbm2java
 */
public class OrdenMedico  implements java.io.Serializable {


     private BigDecimal codDiagnostico;
     private Diagnostico diagnostico;
     private char estado;
     private Date fechaEjecucion;
     private Set muestras = new HashSet(0);

    public OrdenMedico() {
    }

	
    public OrdenMedico(Diagnostico diagnostico, char estado, Date fechaEjecucion) {
        this.diagnostico = diagnostico;
        this.estado = estado;
        this.fechaEjecucion = fechaEjecucion;
    }
    public OrdenMedico(Diagnostico diagnostico, char estado, Date fechaEjecucion, Set muestras) {
       this.diagnostico = diagnostico;
       this.estado = estado;
       this.fechaEjecucion = fechaEjecucion;
       this.muestras = muestras;
    }
   
    public BigDecimal getCodDiagnostico() {
        return this.codDiagnostico;
    }
    
    public void setCodDiagnostico(BigDecimal codDiagnostico) {
        this.codDiagnostico = codDiagnostico;
    }
    public Diagnostico getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(Diagnostico diagnostico) {
        this.diagnostico = diagnostico;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Date getFechaEjecucion() {
        return this.fechaEjecucion;
    }
    
    public void setFechaEjecucion(Date fechaEjecucion) {
        this.fechaEjecucion = fechaEjecucion;
    }
    public Set getMuestras() {
        return this.muestras;
    }
    
    public void setMuestras(Set muestras) {
        this.muestras = muestras;
    }




}


