package model;
// Generated Nov 21, 2016 7:45:14 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private String username;
     private Usuario usuario;
     private char estado;
     private Set citaMedicas = new HashSet(0);
     private Set historialClinicos = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(Usuario usuario, char estado) {
        this.usuario = usuario;
        this.estado = estado;
    }
    public Paciente(Usuario usuario, char estado, Set citaMedicas, Set historialClinicos) {
       this.usuario = usuario;
       this.estado = estado;
       this.citaMedicas = citaMedicas;
       this.historialClinicos = historialClinicos;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Set getCitaMedicas() {
        return this.citaMedicas;
    }
    
    public void setCitaMedicas(Set citaMedicas) {
        this.citaMedicas = citaMedicas;
    }
    public Set getHistorialClinicos() {
        return this.historialClinicos;
    }
    
    public void setHistorialClinicos(Set historialClinicos) {
        this.historialClinicos = historialClinicos;
    }




}


