package model;
// Generated Oct 30, 2016 1:24:18 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * RecetaMedica generated by hbm2java
 */
public class RecetaMedica  implements java.io.Serializable {


     private BigDecimal codDiagnostico;
     private Diagnostico diagnostico;

    public RecetaMedica() {
    }

    public RecetaMedica(Diagnostico diagnostico) {
       this.diagnostico = diagnostico;
    }
   
    public BigDecimal getCodDiagnostico() {
        return this.codDiagnostico;
    }
    
    public void setCodDiagnostico(BigDecimal codDiagnostico) {
        this.codDiagnostico = codDiagnostico;
    }
    public Diagnostico getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(Diagnostico diagnostico) {
        this.diagnostico = diagnostico;
    }




}


