package model;
// Generated Nov 24, 2016 2:14:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Triaje generated by hbm2java
 */
public class Triaje  implements java.io.Serializable {


     private BigDecimal codDiagnostico;
     private Diagnostico diagnostico;
     private String motivoConsulta;
     private BigDecimal peso;
     private BigDecimal presion;
     private BigDecimal talla;
     private String observacion;
     private String enfermera;

    public Triaje() {
    }

	
    public Triaje(Diagnostico diagnostico, String motivoConsulta, BigDecimal peso, BigDecimal presion, BigDecimal talla, String enfermera) {
        this.diagnostico = diagnostico;
        this.motivoConsulta = motivoConsulta;
        this.peso = peso;
        this.presion = presion;
        this.talla = talla;
        this.enfermera = enfermera;
    }
    public Triaje(Diagnostico diagnostico, String motivoConsulta, BigDecimal peso, BigDecimal presion, BigDecimal talla, String observacion, String enfermera) {
       this.diagnostico = diagnostico;
       this.motivoConsulta = motivoConsulta;
       this.peso = peso;
       this.presion = presion;
       this.talla = talla;
       this.observacion = observacion;
       this.enfermera = enfermera;
    }
   
    public BigDecimal getCodDiagnostico() {
        return this.codDiagnostico;
    }
    
    public void setCodDiagnostico(BigDecimal codDiagnostico) {
        this.codDiagnostico = codDiagnostico;
    }
    public Diagnostico getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(Diagnostico diagnostico) {
        this.diagnostico = diagnostico;
    }
    public String getMotivoConsulta() {
        return this.motivoConsulta;
    }
    
    public void setMotivoConsulta(String motivoConsulta) {
        this.motivoConsulta = motivoConsulta;
    }
    public BigDecimal getPeso() {
        return this.peso;
    }
    
    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }
    public BigDecimal getPresion() {
        return this.presion;
    }
    
    public void setPresion(BigDecimal presion) {
        this.presion = presion;
    }
    public BigDecimal getTalla() {
        return this.talla;
    }
    
    public void setTalla(BigDecimal talla) {
        this.talla = talla;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getEnfermera() {
        return this.enfermera;
    }
    
    public void setEnfermera(String enfermera) {
        this.enfermera = enfermera;
    }




}


